name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-npm-run.yml
    with:
      command: check

  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22
          - 20
          - 18
    steps:
      - uses: ./.github/workflows/reusable-npm-run.yml
        with:
          command: test-ci
          node-version: ${{ matrix.node-version }}

  peer:
    needs: [lint, test]
    name: Check peerDependencies issues
    uses: ./.github/workflows/reusable-npm-run.yml
    with:
      command: check-peer-compatibility

  types:
    needs: [lint, test]
    uses: ./.github/workflows/ts-internal.yml

  compatibility-semistandard:
    needs: [lint, test]
    uses: ./.github/workflows/compatibility.yml
    with:
      moduleSet: semistandard-filtered
      flags: --semi

  compatibility-standard:
    needs: [lint, test]
    uses: ./.github/workflows/compatibility.yml
    with:
      moduleSet: standard-filtered

  compatibility-ts-standard:
    needs: [lint, test]
    uses: ./.github/workflows/compatibility.yml
    with:
      moduleSet: ts-standard-filtered
      flags: '--ts'

